version: '3.9'

services:

  mongo_db:
    container_name: db_server
    image: mongo:latest
    restart: always
    volumes:
      - "mongo_db:/data/db"

  
  my_node:
    container_name: node_server
    restart: always
    build: .
    ports: 
      - 5400:3005

    environment:
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: myDB
      NAME: aya

    depends_on:
      - mongo_db

volumes:
  mongo_db: {}
